language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t chucholuco/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true chucholuco/react-test npm test

after_success:
  - docker build -t chucholuco/multi-client ./client
  - docker build -t chucholuco/multi-nginx ./nginx
  - docker build -t chucholuco/multi-server ./server
  - docker build -t chucholuco/multi-worker ./worker